server:
  port: 7072

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:postgresql://localhost:5433/event_service_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

jwt:
  secret: my-secret-key-my-secret-key-my-secret-key
  expiration: 86400000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] [%thread] %logger{36} - %msg%n"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus 
  endpoint:
    health:
      show-details: always      				